export const json = [{
    title: "Mars 45",
    legend: "De retour en hispanie, César bat les derniers partisans de Pompée, ses deux fils Cnaeus et Sextus, à Munda. C'est la fin de la guerre civile.",
    date: "76 av JC",
        xT: 50,
        yT: 330,
        wT:136,
        wL:265,
        id:"v8",
        imgOffX:-30,
        imgOffY:352,
        imgW:360,
        tOX:170,
        tOY:-330,
        wWait:190,
        xWait:11,
        yWait:755,
        hTxt:106
}, {
    title: "Mars - Avril<br/>46",
    legend: "César continue à combattre les partisans de Pompée en Afrique. La bataille décisive se déroule en avril 46 à Thapsus. Caton, allié de Pompée, préfère se donner la mort plutôt que de tomber aux mains annemies et d'assister à la fin de la République.",
    date: "62 av JC",
        xT: 180,
        yT: 835,
        wT:208,
        wL:300,
        id:"v7",
        imgOffX:-66,
        imgOffY:345,
        imgW:380,
        tOX:160,
        tOY:-150,
        wWait:160,
        xWait:205,
        yWait:326,
        hTxt:156
}, {
    title: "Octobre 48",
    legend: "Lorsque César arrive en Egypte, Ptolémée XIII lui offre la tête de Pompée. Ce dernier est horrifié : il n'accepte pas qu'un général romain soit tué par un étranger. Peut-être est-il aussi soulagé de ne pas avoir à tuer lui-même son adversaire !",
    date: "76 av JC",
        xT: 480,
        yT: 398,
        wT:188,
        wL:300,
        id:"v6",
        imgOffX:0,
        imgOffY:360,
        imgW:360,
        tOX:100,
        tOY:-90,
        wWait:150,
        xWait:110,
        yWait:758,
        hTxt:140
}, {
    title: "Octobre 48",
    legend: "Pompée est assassiné sur ordre de Ptolémée XIII, mal conseillé par ses ministres. Il est décapité, son corps est incinéré.",
    date: "84 av JC",
        xT: 695,
        yT: 800,
        wT:188,
        wL:342,
        id:"v5",
        imgOffX:-20,
        imgOffY:286,
        imgW:420,
        tOX:120,
        tOY:-70,
        wWait:240,
        xWait:120,
        yWait:388,
        hTxt:72
}, {
    title: "Août 48",
    legend: "Avec une armée inférieure en nombre et après une bataille incertaine, César remporte la victoire sur Pompée à Pharsale. Pompée fuit en égypte où il compte bénéficier de l'aide du jeune pharaon Ptolémée XIII, dont il a été le tuteur.",
    date: "34 av JC",
        xT: 905,
        yT: 430,
        wT:140,
        wL:260,
        id:"v4",
        imgOffX:-50,
        imgOffY:316,
        imgW:410,
        tOX:0,
        tOY:-220,
        wWait:190,
        xWait:162,
        yWait:642,
        hTxt:172
}, {
    title: "Janvier 48",
    legend: "César traverse la mer Adriatique à la poursuite de Pompée.",
    date: "37 av JC",    
        xT: 1200,
        yT: 800,
        wT:176,
        wL:270,
        id:"v3",
        imgOffX:-80,
        imgOffY:316,
        imgW:400,
        tOX:124,
        tOY:-70,
        wWait:340,
        xWait:30,
        yWait:390,
        hTxt:56
}, {
    title: "Juin - Août<br/>49",
    legend: "César combat les chefs pompéines, Afranius et Petreius, autour de la ville d'Ilerda en Hispanie. Il remporte la victoire au bout de 40 jours.",
    date: "30 av JC",
        xT: 1240,
        yT: 440,
        wT:196,
        wL:300,
        id:"v2",
        imgOffX:-25,
        imgOffY:294,
        imgW:400,
        tOX:250,
        tOY:-280,
        wWait:210,
        xWait:170,
        yWait:578,
        hTxt:106
}, {
    title: "Février - Mars<br/>49",
    legend: "Pompée quitte l'Italie pour la Grèce. César renonce à le poursuivre et se dirige vers l'Hispanie où sont stationnées des armées fidèles à Pompée. Chemin faisant, il entreprend le siège de Marseille, qui s'est ralliée à Pompée.",
    date: "80 av JC",
        xT: 1560,
        yT: 750,
        wT:228,
        wL:260,
        id:"v1",
        imgOffX:20,
        imgOffY:126,
        imgW:340,
        tOX:70,
        tOY:-90,
        wWait:150,
        xWait:60,
        yWait:150,
        hTxt:157
}]